### PR TITLE
wait for css files to load before returning the svelte instance

### PR DESCRIPTION
**Pull request by JohnnyFun**
fixes https://github.com/bahmutov/cypress-svelte-unit-test/issues/250

### CODE REVIEW

**Comment by JohnnyFun** [comment]
I didn't test this manually very much. Relying on the repo's tests to let me know if I messed anything up...

**Comment by JohnnyFun** [comment]
Ideally a test would be added that asserts cssFile option works. But gotta sleep...

**Comment by alejandroiglesias** [comment]
@bahmutov did you have a chance to look at this? It would unblock some test specs for me as I described in #250.

**Comment by JohnnyFun** [comment]
Sure, I bet I can add one to this spec and just assert that `$set` exists on the resolved object: https://github.com/bahmutov/cypress-svelte-unit-test/blob/master/cypress/components/styles/styles-spec.js

**Comment by JohnnyFun** [comment]
Ok, I added a test and confirmed it breaks without my change and passes with it.

**Comment by JohnnyFun** [comment]
Ok, looks like all tests pass--I had not yet pushed when I made my previous comment, so apologies if that caused any confusion.

**Comment by bahmutov** [comment]
Super, thank you very, much, merging now

**Pull request merged**
