### PR TITLE
fix(index): events fired on document and window work

### PR DESCRIPTION
**Pull request by JohnnyFun**
Fixes: https://github.com/bahmutov/cypress-svelte-unit-test/issues/60

### CODE REVIEW

**Comment by bahmutov** [comment]
Let me take a look - why isn't CI running, ughh

**Comment by JohnnyFun** [comment]
fwiw, the `npm run size` was failing for me, so I skipped that pre-push task...sorry if that's the cause. 

image

**Comment by JohnnyFun** [comment]
Oh also, if this looks good, this may also be an issue in cypress-react-unit-tests, but didn't confirm.

And thanks for writing this! Being able to test our svelte components has been super nice.

**Comment by JohnnyFun** [comment]
hmm, looks like more document functionality needs to be copied over in some situations. 

For instance, we wrap an npm package 'tributejs' which uses methods like `document.body.appendChild` to build its UI. So to get our svelte wrapper component working, I also needed to copy over a bunch of that functionality. Maybe there's a cleaner way?

```

function bindDocumentFunctionality(cyDocument) {
	const documentMethods = [
		'addEventListener',
		'removeEventListener',
		'createElement',
		'createTextNode',
		'createDocumentFragment',
		'createRange',
		'querySelector',
		'getElementById',
		'getElementsByTagName',
		'getElementsByClassName'
	]
	documentMethods.forEach(m => document[m] = cyDocument[m].bind(cyDocument))

	const documentBodyMethods = [
		'append',
		'appendChild',
		'removeChild',
		'removeAttribute',
		'remove',
		'createTextRange',
		'setAttribute',
		'getBoundingClientRect',
		'hasAttribute',
		'getAttribute'
	]
	documentBodyMethods.forEach(m => {
		if (document.body[m])
			document.body[m] = cyDocument.body[m].bind(cyDocument.body)
	})

	document.body.classList.add = cyDocument.body.classList.add.bind(cyDocument.body)
	document.body.classList.remove = cyDocument.body.classList.remove.bind(cyDocument.body)
}
```

**Comment by bahmutov** [comment]
thank you @JohnnyFun - closing in favor of #62 where I copied your example

**Pull request closed without merging**
